config/routes.rb
Rails.application.routes.draw do
  resources :review_mobiles
  resources :reviews
  resources :menus, :menus_mobile
  resources :photos, :photos_mobile
  root :to => "first_page#index"
  devise_for :users
  resources :restaurants, :restaurants_mobile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
  has_one :state
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
  mount_uploader :menu, ImageUploader
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :restaurant
  mount_uploader :photo, ImageUploader
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_one :city
  has_one :category
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/models/review_mobile.rb
class ReviewMobile < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.where("restaurant_id = " + params[:restaurant_id])
    @restaurant_id = params[:restaurant_id]
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
    @menu.restaurant_id = params[:restaurant_id]
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:restaurant_id, :menu, :price)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.where("restaurant_id = " + params[:restaurant_id])
    @restaurant_id = params[:restaurant_id]
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
    @photo.restaurant_id = params[:restaurant_id]
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:restaurant_id, :photo)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.where("restaurant_id = " + params[:restaurant_id])
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:place, :price, :attendance, :food, :descriprion, :restaurant_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_page_helper.rb
module FirstPageHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/menus_mobile_helper.rb
module MenusMobileHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/photos_mobile_helper.rb
module PhotosMobileHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/review_mobiles_helper.rb
module ReviewMobilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/reviews_mobile_helper.rb
module ReviewsMobileHelper
end

app/views/menus/_form.html.erb
<%= form_for(menu) do |f| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="display: none">
    <%= f.label :restaurant_id %>
    <%= f.text_field :restaurant_id %>
  </div>

  <div class="field">
    <%= f.label :menu, 'Produto:' %>
    <%= f.file_field :menu %>
  </div>
  
  <div class="field">
    <%= f.label :price, 'Preço:' %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editar produto</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Voltar', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Voltar', {controller: "restaurants", action: "index"}, class: "btn btn-default" %>

<h1>Produtos</h1>

<table class="table">
  <!--<thead>
    <tr>
      <th style="display: none">Restaurant</th>
      <th>Produto</th>
      <th>Preço</th>
      <th colspan="3"></th>
    </tr>
  </thead>-->

  <!--<tbody class="row">
    <% @menus.each do |menu| %>
      <tr class="col-md-3">
        <td style="display: none"><%= menu.restaurant_id %></td>
        <div class="row">
          <div class="col-lg-12">
            <td><%= link_to (image_tag menu.menu.thumb.url), menu, class:"btn btn-link" %></td>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <td><%= menu.price %></td>
            <td><%= link_to 'Excluir', menu, method: :delete, data: { confirm: 'Deseja mesmo excluir o produto?' }, class:"btn btn-link" %></td>
            </div>
        </div>
      </tr>
    <% end %>
  </tbody>-->
</table>

<div class="row">
  <% @menus.each do |menu| %>
    <div class="col-md-2">
      <div style="display: none"><%= menu.restaurant_id %></div>
      <div class="row">
        <div class="col-md-12">
          <div style="height: 200px;"><%= link_to (image_tag menu.menu.thumb.url), menu, class:"btn btn-link btn-img" %></div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= link_to 'Excluir', menu, method: :delete, data: { confirm: 'Deseja mesmo excluir o produto?' }, class:"btn btn-link" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'Adicionar produto', {controller: "menus", action: "new", restaurant_id: @restaurant_id }, class: "btn btn-primary" %>

app/views/menus/new.html.erb
<h1>Novo produto</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Voltar', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p style="display: none">
  <strong>Restaurant:</strong>
  <%= @menu.restaurant_id %>
</p>

<p>
  <strong>Produto:</strong>
  <%= image_tag @menu.menu.thumb.url %>
</p>

<%= link_to 'Editar', edit_menu_path(@menu), class: "btn btn-primary"%> |
<%= link_to 'Voltar', {controller: "menus", action: "index", restaurant_id: @menu.restaurant_id}, class: "btn btn-default" %>

app/views/photos/_form.html.erb
<%= form_for(photo) do |f| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="display: none">
    <%= f.label :restaurant_id %>
    <%= f.text_field :restaurant_id %>
  </div>

  <div class="field">
    <%= f.label :photo, 'Foto' %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Voltar', {controller: "restaurants", action: "index"}, class: "btn btn-default" %>

<h1>Fotos</h1>

<table class="table">
  <thead>
    <tr>
      <th style="display: none">Restaurant</th>
      <th>Foto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td style="display: none"><%= photo.restaurant_id %></td>
        <td><%= image_tag photo.photo.thumb.url %></td>
        <td><%= link_to 'Visualizar', photo, class:"btn btn-link" %></td>
        <td><%= link_to 'Excluir', photo, method: :delete, data: { confirm: 'Deseja mesmo excluir a foto?' }, class:"btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar foto', {controller: "photos", action: "new", restaurant_id: @restaurant_id }, class: "btn btn-primary" %>

app/views/photos/new.html.erb
<h1>Adicionar foto</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p style="display: none">
  <strong>Restaurant:</strong>
  <%= @photo.restaurant_id %>
</p>

<p>
  <strong>Foto:</strong>
  <%= image_tag @photo.photo.thumb.url %>
</p>

<%= link_to 'Editar', edit_photo_path(@photo) %> |
<%= link_to 'Voltar', {controller: "photos", action: "index", restaurant_id: @photo.restaurant_id} %>